CREATE TABLE IF NOT EXISTS userprofiles(
    ID BIGINT(20) NOT NULL AUTO_INCREMENT ,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS recipe(
    ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL
);